# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:

    - name: First interaction
      uses: actions/first-interaction@v1.3.0
      with: 
    # Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}
       repo-token: ${{ secrets.GITHUB_TOKEN }} 
    # Comment to post on an individual's first issue
       issue-message: "Hey! I noticed it's your first issue! Good Job! Contributors will be with you soon." # optional
    # Comment to post on an individual's first pull request
       pr-message: "Hello! Wait until the owner accepts this request."
